# Must match functions.src/app.py.maxDuration in vercel.json.
VERCEL_MAX_DURATION_SECONDS = 800

VAST_WORKER_TIMEOUT_SECONDS = 600.0
VAST_REQUEST_TIMEOUT_SECONDS = 720.0
VAST_REQUEST_COST = 100
VAST_MAX_RETRIES = 2

QSTASH_RETRIES = 2
QSTASH_TIMEOUT = "810s"
QSTASH_RETRY_DELAY = "pow(2, retried) * 1000"
QSTASH_FLOW_CONTROL_KEY = "vast-wan-generate"
QSTASH_FLOW_CONTROL_PARALLELISM = 1
